language: ruby
rvm:
- 2.0.0
script:
- RAILS_ENV=test COVERAGE=true bundle exec rake --trace db:migrate spec cucumber
branches:
  only:
  - master
  - production
notifications:
  email:
    recipients:
    - gmacie@hotmail.com
    on_success: change
    on_failure: always
env:
  global:
after_success:
  - wget -qO- https://toolbelt.heroku.com/install-ubuntu.sh | sh
  - echo "Host heroku.com" >> ~/.ssh/config
  - echo "   StrictHostKeyChecking no" >> ~/.ssh/config
  - echo "   CheckHostIP no" >> ~/.ssh/config
  - echo "   UserKnownHostsFile=/dev/null" >> ~/.ssh/config
  - # heroku keys:clear
  - # yes | heroku keys:add
  - # yes | git push heroku master
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
