language: ruby
rvm:
- 2.0.0
script:
- RAILS_ENV=test COVERAGE=true bundle exec rake --trace db:migrate spec cucumber
branches:
  only:
  - master
  - production
notifications:
  email:
    recipients:
    - gmacie@hotmail.com
    on_success: change
    on_failure: always
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
env:
  global:
    secure: ZB3cJsUoaPMAp9dTycSQFtP47sMOD6bmOt7uaY9WLZ0bbg7BrjkD1pShYDa6ZyUo8FzGkvnAEjUojFT8LICdgT7uFMREIU+c46MnOb6m9/6AHM/m0vJzNfYO1eW8wOGr8Lzp6Cn+kYsrHCC2Bar503c1FfRDihKP1SUubJwSC68=
after_success:
- wget -qO- https://toolbelt.heroku.com/install-ubuntu.sh | sh
- git remote add heroku git@heroku.com:civicspaces.git
- echo "Host heroku.com" >> ~/.ssh/config
- echo "   StrictHostKeyChecking no" >> ~/.ssh/config
- echo "   CheckHostIP no" >> ~/.ssh/config
- echo "   UserKnownHostsFile=/dev/null" >> ~/.ssh/config
- heroku keys:clear
- yes | heroku keys:add
- yes | git push heroku master
